name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/terraform.yaml"

  workflow_dispatch: {}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Verify installation
      - name: Terraform Version
        run: terraform version

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Terraform Init
      - name: Terraform init
        run: terraform init
        working-directory: "../../environments/dev"

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: "../../environments/dev"
